<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>rtvAGD</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>42cf4fcc-d4fc-416f-b75e-3b2460eeaa37</testSuiteGuid>
   <testCaseLink>
      <guid>df6e86e6-1508-44f5-9cee-599664316aac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>4130c0b9-73b9-44af-aa05-294cfa200bac</id>
         <masked>false</masked>
         <name>Wyszukanie</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Logowanie/Logowanie_rtvAGD</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>adee2d9f-8691-47ff-87f9-875faddea5f6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/rtvAGD (1)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aba14b27-d2ce-422e-ad35-2b6003d19a86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Wyszukanie</value>
         <variableId>4130c0b9-73b9-44af-aa05-294cfa200bac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Imie</value>
         <variableId>63195913-ff97-48a5-bb48-e8087c8e4c20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nazwisko</value>
         <variableId>8374d3bc-a98c-4bda-9b6c-3468f43daf66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>aacf083b-eb91-4f97-b84f-5532c3a8c340</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Haslo</value>
         <variableId>0950c0cf-85d8-4940-823a-b5298cefb1ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>adee2d9f-8691-47ff-87f9-875faddea5f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Haslo2</value>
         <variableId>39008853-a048-48bd-9beb-25b1c84cd97c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
